version: "3.8"

services:
  myDB:
    image: postgres:15.4
    container_name: my-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=andres-dev
      - POSTGRES_PASSWORD=ShA1245*.
      - POSTGRES_DB=super-db
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4:7.7
    # container_name: pgadmin4
    restart: always
    depends_on:
      - myDB
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=andres@google.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      # - ./pgadmin:/certs/server.cert
      # - ./pgadmin:/certs/server.key
      # - ./pgadmin:/pgadmin4/servers.json
# sudo chown -R 5050:5050 pgadmin  =>  Ejecutar este comando para poder establecer la conexión
# con el contenedor de pgAdmin
